#!/bin/bash

cat << EOF > X601-vendor-blobs.mk
# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/Infinix/X601/setup-makefiles.sh

PRODUCT_COPY_FILES += \\
EOF
cd proprietary
find -type f | sort -t '\0' -n | while read line; do echo "    vendor/Infinix/X601/proprietary/"${line:2}":system/"${line:2}" \\" >> ../X601-vendor-blobs.mk; done
